/*!
 * The MIT License (MIT)
 *
 * Copyright (c) 2019 Mark van Seventer
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

// Strict mode.
'use strict'

// Package modules.

// Configure.
const options = {
  shell: {
    alias: 's',
    choices: ['bash', 'zsh', 'fish', 'powershell'],
    default: 'bash',
    desc: 'Shell type'
  }
}

// Command builder.
const builder = (yargs) => {
  return yargs
    .strict()
    .options(options)
    .example(
      '$0 completions powershell',
      'Generate PowerShell completion script'
    )
    .example(
      '$0 completions bash',
      'Generate Bash completion script'
    )
    .epilog(
      'For more information on generating completions, please visit the project repository.'
    )
    .exitProcess(false)
}

// Command handler.
const handler = (args) => {
  const cmds = [
    'affine', 'bandbool', 'blur', 'boolean', 'clahe', 'composite',
    'convolve', 'ensureAlpha', 'extend', 'extract', 'extractChannel',
    'flatten', 'flip', 'flop', 'gamma', 'greyscale', 'joinChannel',
    'linear', 'median', 'modulate', 'negate', 'normalise',
    'pipelineColourspace', 'recomb', 'removeAlpha', 'resize', 'rotate',
    'sharpen', 'threshold', 'tint', 'tile', 'toColourspace', 'trim', 'unflatten'
  ]
  const shell = args.shell || 'bash'
  if (shell === 'powershell') {
    console.log('# PowerShell completion for sharp CLI')
    console.log('# Generated by: sharp completions powershell')
    console.log('# Usage: sharp completions powershell | Out-File -Encoding UTF8 $PROFILE')
    console.log('')
    cmds.forEach(c => console.log(c))
  } else if (shell === 'bash') {
    console.log('# Bash completion for sharp CLI')
    console.log('# Generated by: sharp completions bash')
    console.log('# Usage: source <(sharp completions bash)')
    console.log('')
    console.log('_sharp() {')
    console.log('    local cur')
    const compWords = String.fromCharCode(36) + '{COMP_WORDS[COMP_CWORD]}'
    console.log('    cur="' + compWords + '"')
    const cmdList = cmds.join(' ')
    const curPlaceholder = String.fromCharCode(36) + 'cur'
    console.log('    COMPREPLY=($(compgen -W "' + cmdList + '" -- ' + curPlaceholder + '))')
    console.log('}')
    console.log('complete -F _sharp sharp')
  } else if (shell === 'zsh') {
    console.log('# Zsh completion for sharp CLI')
    console.log(cmds.join('\n'))
  } else if (shell === 'fish') {
    console.log('# Fish completion for sharp CLI')
    console.log(cmds.join('\n'))
  }
  // Exit immediately to skip global option validation
  process.exit(0)
}

// Exports.
module.exports = {
  command: 'completions [shell]',
  describe: 'Generate shell completion scripts',
  builder,
  handler
}
